// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/app_uninstalled": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/api/events/impression": {
    params: {};
  };
  "/api/friendly-brands": {
    params: {};
  };
  "/api/friendly-brands/:id": {
    params: {
      "id": string;
    };
  };
  "/api/activate-code": {
    params: {};
  };
  "/api/onboarding": {
    params: {};
  };
  "/api/settings": {
    params: {};
  };
  "/api/offers": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/r/:offerId": {
    params: {
      "offerId": string;
    };
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/html": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/webhooks/app_uninstalled" | "/webhooks/orders/create" | "/api/events/impression" | "/api/friendly-brands" | "/api/friendly-brands/:id" | "/api/activate-code" | "/api/onboarding" | "/api/settings" | "/api/offers" | "/auth/login" | "/r/:offerId" | "/auth/*" | "/app" | "/app/additional" | "/app/onboarding" | "/app/html";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.app_uninstalled.tsx": {
    id: "routes/webhooks.app_uninstalled";
    page: "/webhooks/app_uninstalled";
  };
  "routes/webhooks.orders.create.tsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/api.events.impression.ts": {
    id: "routes/api.events.impression";
    page: "/api/events/impression";
  };
  "routes/api.friendly-brands.tsx": {
    id: "routes/api.friendly-brands";
    page: "/api/friendly-brands" | "/api/friendly-brands/:id";
  };
  "routes/api.friendly-brands.$id.tsx": {
    id: "routes/api.friendly-brands.$id";
    page: "/api/friendly-brands/:id";
  };
  "routes/api.activate-code.ts": {
    id: "routes/api.activate-code";
    page: "/api/activate-code";
  };
  "routes/api.onboarding.tsx": {
    id: "routes/api.onboarding";
    page: "/api/onboarding";
  };
  "routes/api.settings.tsx": {
    id: "routes/api.settings";
    page: "/api/settings";
  };
  "routes/api.offers.ts": {
    id: "routes/api.offers";
    page: "/api/offers";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/r.$offerId.jsx": {
    id: "routes/r.$offerId";
    page: "/r/:offerId";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/additional" | "/app/onboarding" | "/app/html";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.onboarding.tsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.html.tsx": {
    id: "routes/app.html";
    page: "/app/html";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.app_uninstalled": typeof import("./app/routes/webhooks.app_uninstalled.tsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.tsx");
  "routes/api.events.impression": typeof import("./app/routes/api.events.impression.ts");
  "routes/api.friendly-brands": typeof import("./app/routes/api.friendly-brands.tsx");
  "routes/api.friendly-brands.$id": typeof import("./app/routes/api.friendly-brands.$id.tsx");
  "routes/api.activate-code": typeof import("./app/routes/api.activate-code.ts");
  "routes/api.onboarding": typeof import("./app/routes/api.onboarding.tsx");
  "routes/api.settings": typeof import("./app/routes/api.settings.tsx");
  "routes/api.offers": typeof import("./app/routes/api.offers.ts");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/r.$offerId": typeof import("./app/routes/r.$offerId.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.onboarding": typeof import("./app/routes/app.onboarding.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.html": typeof import("./app/routes/app.html.tsx");
};